# Generated by Django 2.2.1 on 2019-10-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contet',
            new_name='content',
        ),
    ]
